/**
 * Created by Marko on 7/8/2015.
 */
module FON{
    declare var breeze:any;

    export class StudentPreviewAllModel{
        public entityManager: any;

        constructor (){
            this.entityManager = this._createEntityManager();

            this._loadData(this.entityManager);
        }

        /*get entityManager(): any {
            return this._entityManager;
        }*/

        private _createEntityManager(){
            var ms = new breeze.MetadataStore();

            var personType = new breeze.EntityType( {
                shortName: "Student",
                autoGeneratedKeyType: breeze.AutoGeneratedKeyType.Identity
            });

            var idProp = new breeze.DataProperty( {
                name: 'id',
                dataType: breeze.DataType.Int32,
                isPartOfKey: true
            });
            personType.addProperty(idProp);

            var firstNameProp = new breeze.DataProperty( {
                name: 'firstName',
                dataType: breeze.DataType.String,
                maxLength: 10,
                validators: [breeze.Validator.maxLength( {maxLength: 10})]
            });
            personType.addProperty(firstNameProp);

            var lastNameProp = new breeze.DataProperty( {
                name: "lastName",
                dataType: breeze.DataType.String,
                maxLength: 10,
                validators: [breeze.Validator.maxLength( {maxLength: 10})]
            });
            personType.addProperty(lastNameProp);

            ms.addEntityType(personType);

            return new breeze.EntityManager( {
                metadataStore: ms
            });
        }

        private _loadData(entityManager){
            var student = entityManager.createEntity("Student");
            student.setProperty("id", 1);
            student.setProperty("firstName", "Marko");
            student.setProperty("lastName", "Petrovic");

            student = entityManager.createEntity("Student");
            student.setProperty("id", 2);
            student.setProperty("firstName", "Milos");
            student.setProperty("lastName", "Nedeljkovic");

            student = entityManager.createEntity("Student");
            student.setProperty("id", 3);
            student.setProperty("firstName", "Tanja");
            student.setProperty("lastName", "Petrovic");

            student = entityManager.createEntity("Student");
            student.setProperty("id", 4);
            student.setProperty("firstName", "Jovan");
            student.setProperty("lastName", "Petrovic");

            student = entityManager.createEntity("Student");
            student.setProperty("id", 5);
            student.setProperty("firstName", "Simona");
            student.setProperty("lastName", "Petrovic");
        }
    }
}